### ISSUE TITLE
New rule to compare 2 columns (<,>,=)

### ISSUE THREAD

**Issue by Ju11y** [kiwicom/contessa#20]
Add rule to contessa for comparison of 2 cols. 

Probably the current ones could be extended (e.g. gt, gte, lt, lte) to support column name, not only the number.

But its just an idea, so design it freely.

**Comment by maroshmka** [comment]
I kinda accidentaly allowed this feature from the beginning 😅 . you just need to use column name as "value". E.g 
```
{"name": "not", "column": "src", "value": "dst"}
```
This will check if src != dst. Should work for all rules. 

I made a PR #26 to deprecate `NotColumnRule` as it is not needed + also add more tests for it. 
@Ju11y, are you okey with such implementation ? Or is the "value" as a column name a bit confusing? we could rename it e.g. to "column", but it would require a lot more implementation of course :D

**Comment by Ju11y** [comment]
Great, so less work for you :D 
We didn't know that it was possible to use attribute name there.
Does this work for all the rules (gt, gte, lt, lte, eq)?

I think that you don't have to rename it. It is ok with "value", we just need to know how to use it and you showed a nice example :)

Could you please wait until tomorrow wit deprecating `NotColmunRule` ? We have some checks that use it and need to switch it to new logic.

**Comment by maroshmka** [comment]
yop, i didnt know it eaither 🤷🏽‍♂️ or at least havent realised it until
today.

dont worry about the merge, not gonna affect current version.

yea, should work for those rules. i added test for that. maybe try it out
locally and report a bug if you see something.

Dňa po 26. 8. 2019 o 17:03 Ju11y <notifications@github.com> napísala(a):

**Comment by maroshmka** [comment]
PR was merged, closing this
