### ISSUE TITLE
Add way to compare 2 or more tables (e.g. count of rows)

### ISSUE THREAD

**Issue by Ju11y** [kiwicom/contessa#21]
Design/implement new rule that would let us compare the data from two or more tables.

**Comment by junckritter** [comment]
@Ju11y Can you please write simple example of the proposed usage? Because if the description should be taken literally, we need completely new runner which operates on 2 (multiple) tables. 

Another possibility (without big changes in *Contessa*) would be to compare the results of same set of rules on those 2 tables.

**Comment by Ju11y** [comment]
Well, the idea was to compare the count of rows in two tables. We are currently doing this using consistency checker made by Dominik. He would like to discuss this issue with you (I am not able to tag him)

**Comment by maroshmka** [comment]
oh I forgot about this 😅

Tomas pls, take a look on the consistency checker that Dominik wrote and
think about how to integrate that into the Contessa.

Dňa pi 11. 10. 2019, 16:53 Ju11y <notifications@github.com> napísal(a):

**Comment by junckritter** [comment]
After consulting with Dominik about existing solution, we've identified basic requirement:
It should be possible to compare the results of 2 SQL-queries (run against 2 respective tables). The result can be in form of scalar value (count of rows, sum from 1 column) or vector (set of PKs).

For the technical solution: the new "multi"-runner (2 connections/DBs, 2 queries) seems as proper way to do this.

**Comment by junckritter** [comment]
Ok, fine by me. I'd leave `Runner` in the name for now

**Comment by junckritter** [comment]
Will be implemented after #41 is done , as a *CountComparator*.

**Comment by dee-gmiterko** [comment]
done
